listen              1935;
max_connections     1000;
daemon              off;
srs_log_tank        console;

http_api {
    enabled         on;
    listen          1985;
}

http_server {
    enabled         on;
    listen          8080;
}

stats {
    network         0;
}

srt_server {
    enabled         on;
    listen          10080;
    maxbw           1000000000;
    connect_timeout 4000;
    peerlatency     300;
    recvlatency     300;
}

vhost __defaultVhost__ {
    srt {
        enabled     on;
        srt_to_rtmp on;
    }
}
