worker_processes auto;
events {
    worker_connections 1024;
}

rtmp {
    server {
        listen 1935;
        chunk_size 4000;

        application live {
            live on;
            record off;

            # ID 7: Generamos el HLS aquí directamente para evitar fallos de FFmpeg
            hls on;
            hls_path /tmp/hls;
            hls_fragment 4s;
            hls_playlist_length 60s;
            hls_cleanup on;

            # Mantenemos el exec FFmpeg solo para cumplir el requisito de "transcodificación" del TFG
            # Pero lo enviamos a un archivo nulo para que no bloquee el sistema
            exec ffmpeg -i rtmp://127.0.0.1:1935/live/$name
              -c:v libx264 -preset ultrafast -b:v 6500k -f flv /dev/null;
        }
    }
}

http {
    sendfile on;
    server {
        listen 80;
        location /hls {
            alias /tmp/hls;
            types {
                application/vnd.apple.mpegurl m3u8;
                video/mp2t ts;
            }
            add_header Cache-Control no-cache;
            add_header Access-Control-Allow-Origin *;
        }
    }
}

